### ISSUE TITLE
URL Open Error

### ISSUE THREAD

**Issue by Bhaney44** [ejbaran/algorand-tutorials-python#1]
I'm working through the [LaylaCoin Tutorial](https://developer.algorand.org/tutorials/create-dogcoin/) in the Algorand Developer Portal. First of all, Layla is too cute. Second, I made it pretty smoothly through step two, creating addresses and passphrases, as well as a hash for `LaylaGyoza.jpg`. But, I ran into a problem on step three.  

```
>>> from main import create
>>> from config import creator_passphrase
>>> create(creator_passphrase)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/brianhaney/node/LaylaCoin/main.py", line 22, in create
    data = add_network_params(asset_details, client)
  File "/Users/brianhaney/node/LaylaCoin/util.py", line 44, in add_network_params
    params = client.suggested_params()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/algosdk/algod.py", line 245, in suggested_params
    return self.algod_request("GET", req, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/algosdk/algod.py", line 75, in algod_request
    resp = urlopen(req)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 548, in _open
    'unknown_open', req)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1387, in unknown_open
    raise URLError('unknown url type: %s' % type)
urllib.error.URLError: <urlopen error unknown url type: 127.0.0.1>
```

I'm working on debugging this now. My first impression is this is a url error, but I am not sure where exactly the url error is coming from. The error `<urlopen error unknown url type: 127.0.0.1>` directed me to `config.py` where I set the `algod_address`.

```
# Credentials to connect through an algod client
algod_address = "127.0.0.1:8080"
```

I got the address by running `cat $ALGORAND_DATA/algod.net`, but I am not sure this is the correct data to include in setting the `algod_address` variable. I think this is my error for not inputting the right data to the variable.

**Comment by Bhaney44** [comment]
I found the error. I did not connect an algod client to a TestNet node first. I was running my node on `mainnet-v1.0`. The tutorial states: 

"Some of these extra parameters rely on some network state (like current round) so we will need an algod client connected to a TestNet node. Open `config.py` and enter values for your `algod_address` and `algod_token` for TestNet." 

So, I am going to work on setting up a client connected to a TestNet node. And then run `create(creator_passphrase)` again.

**Comment by Bhaney44** [comment]
**Update** 
I successfully switched to the TestNet by replacing the genesis json file. However, I am still getting the URL error running:

```
>>> from main import create
>>> from config import creator_passphrase
>>> create(creator_passphrase)
```

Error:
`urllib.error.URLError: <urlopen error [Errno 61] Connection refused>`

The problem is in `config.py ` the code reads:

`algod_address = "https://api.host.com"`

I know the URL is wrong, but I have no idea what a correct `algod_address` would look like. I tried using:

`algod_address = "GYOVUXBMA5C55BI4YO27WKI4QQIMXJHVXMMCFKEOJMZV6TRJJDJ6V6NTAU"`

from the receiver address in the tutorial, but I got the same URL error.

**Comment by Bhaney44** [comment]
**Update**

I switched the config file back to:

`algod_address = "127.0.0.1:8080"`

I think this is the correct address. But I am still getting the same error:

```
(AlgoEnv) Brians-MacBook-Pro:LaylaCoin brianhaney$ python3 run.py
Traceback (most recent call last):
  File "run.py", line 14, in <module>
    create(creator_passphrase)
  File "/Users/brianhaney/node/LaylaCoin/main.py", line 22, in create
    data = add_network_params(asset_details, client)
  File "/Users/brianhaney/node/LaylaCoin/util.py", line 44, in add_network_params
    params = client.suggested_params()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/algosdk/algod.py", line 245, in suggested_params
    return self.algod_request("GET", req, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/algosdk/algod.py", line 75, in algod_request
    resp = urlopen(req)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 548, in _open
    'unknown_open', req)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1387, in unknown_open
    raise URLError('unknown url type: %s' % type)
urllib.error.URLError: <urlopen error unknown url type: 127.0.0.1>
```
It still seems like there is a URL error. I would sincerely appreciate any thoughts or suggestions. Thanks!

**Comment by Bhaney44** [comment]
**Update**

I fixed the URL error. The solution was that the `algod_address`  variable has to take the following form:

`algod_address = "http://localhost:4001"`

The last four digits are unique for each node and can be found by running:

`cat $ALGORAND_DATA/algod.net`

However, I have a new error now.

```
(AlgoEnv) Brians-MacBook-Pro:LaylaCoin brianhaney$ python3 run.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/algosdk/algod.py", line 75, in algod_request
    resp = urlopen(req)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400: Bad Request

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run.py", line 14, in <module>
    create(creator_passphrase)
  File "/Users/brianhaney/node/LaylaCoin/main.py", line 25, in create
    txinfo = sign_and_send(txn, passphrase, client)
  File "/Users/brianhaney/node/LaylaCoin/util.py", line 58, in sign_and_send
    client.send_transaction(stxn, headers={'content-type': 'application/x-binary'})
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/algosdk/algod.py", line 291, in send_transaction
    **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/algosdk/algod.py", line 277, in send_raw_transaction
    return self.algod_request("POST", req, data=txn, headers=tx_headers, **kwargs)["txId"]
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/algosdk/algod.py", line 83, in algod_request
    raise error.AlgodHTTPError(raisex)
algosdk.error.AlgodHTTPError: transaction {_struct:{} Sig:[203 160 120 179 177 71 104 120 240 218 58 79 99 21 58 96 232 225 244 233 203 236 132 66 249 96 45 213 200 13 243 20 29 187 251 248 122 229 120 184 61 110 109 170 227 221 91 222 179 189 134 156 91 29 68 186 92 221 123 23 109 255 121 1] Msig:{_struct:{} Version:0 Threshold:0 Subsigs:[]} Lsig:{_struct:{} Logic:[] Sig:[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0] Msig:{_struct:{} Version:0 Threshold:0 Subsigs:[]} Args:[]} Txn:{_struct:{} Type:acfg Header:{_struct:{} Sender:6U4X6KSDTVNVLNKTQAQUWSVSI4LQGPOMSSO34XUJCDW5CXCUSYUBJLTVCI Fee:{Raw:1000} FirstValid:468624 LastValid:469624 Note:[] GenesisID:testnet-v1.0 GenesisHash:JBR3KGFEWPEE5SAQ6IWU6EEBZMHXD4CZU6WCBXWGF57XBZIJHIRA Group:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA Lease:[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0] RekeyTo:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAY5HFKQ} KeyregTxnFields:{_struct:{} VotePK:[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0] SelectionPK:[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0] VoteFirst:0 VoteLast:0 VoteKeyDilution:0 Nonparticipation:false} PaymentTxnFields:{_struct:{} Receiver:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAY5HFKQ Amount:{Raw:0} CloseRemainderTo:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAY5HFKQ} AssetConfigTxnFields:{_struct:{} ConfigAsset:0 AssetParams:{_struct:{} Total:1000000 Decimals:6 DefaultFrozen:false UnitName:Gyoza AssetName:LaylaCoin URL:LaylaGyoza.jpg MetadataHash:[79 136 253 242 209 254 238 150 43 249 240 182 178 141 13 181 206 100 41 35 155 86 206 164 129 166 185 189 14 247 97 108] Manager:6U4X6KSDTVNVLNKTQAQUWSVSI4LQGPOMSSO34XUJCDW5CXCUSYUBJLTVCI Reserve:6U4X6KSDTVNVLNKTQAQUWSVSI4LQGPOMSSO34XUJCDW5CXCUSYUBJLTVCI Freeze:6U4X6KSDTVNVLNKTQAQUWSVSI4LQGPOMSSO34XUJCDW5CXCUSYUBJLTVCI Clawback:6U4X6KSDTVNVLNKTQAQUWSVSI4LQGPOMSSO34XUJCDW5CXCUSYUBJLTVCI}} AssetTransferTxnFields:{_struct:{} XferAsset:0 AssetAmount:0 AssetSender:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAY5HFKQ AssetReceiver:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAY5HFKQ AssetCloseTo:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAY5HFKQ} AssetFreezeTxnFields:{_struct:{} FreezeAccount:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAY5HFKQ FreezeAsset:0 AssetFrozen:false} ApplicationCallTxnFields:{_struct:{} ApplicationID:0 OnCompletion:NoOpOC ApplicationArgs:[] Accounts:[] ForeignApps:[] ForeignAssets:[] LocalStateSchema:{_struct:{} NumUint:0 NumByteSlice:0} GlobalStateSchema:{_struct:{} NumUint:0 NumByteSlice:0} ApprovalProgram:[] ClearStateProgram:[]} CompactCertTxnFields:{_struct:{} CertRound:0 CertType:0 Cert:{_struct:{} SigCommit:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA SignedWeight:0 SigProofs:[] PartProofs:[] Reveals:map[]}}} AuthAddr:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAY5HFKQ} invalid : asset transaction not supported
```

I will continue debugging as time permits. Thanks!

**Comment by miaoye26** [comment]
Hi, 
I am having similar errors here, would be helpful if author of the code provide an update if there is any issue with existing code base. Tried every thing with multiple accounts, pretty sure I rule those config issue out.

`from config import creator_passphrase
>>> create(creator_passphrase)
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/algosdk/algod.py", line 75, in algod_request
    resp = urlopen(req)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden`


`During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/miaoye26/Repo/algorand-tutorials-python-master/create-layla-coin/main.py", line 22, in create
    data = add_network_params(asset_details, client)
  File "/Users/miaoye26/Repo/algorand-tutorials-python-master/create-layla-coin/util.py", line 48, in add_network_params
    params = client.suggested_params()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/algosdk/algod.py", line 245, in suggested_params
    return self.algod_request("GET", req, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/algosdk/algod.py", line 83, in algod_request
    raise error.AlgodHTTPError(raisex)
algosdk.error.AlgodHTTPError: Missing Authentication Token`

**Comment by Bhaney44** [comment]
Hi @miaoye26 I am still working on figuring this out. It looks like your main error read outs are:

`urllib.error.HTTPError: HTTP Error 403: Forbidden`
`algosdk.error.AlgodHTTPError: Missing Authentication Token`

I am starting up my node and connecting to the Network now. But, I will provide another update with more detail as soon as I get my code running. Hopefully then I can give some feedback on next steps. Happy to collaborate - we got this!

**Comment by iskysun96** [comment]
What client are you guys using? Could you share your code on setting up the client?

**Comment by Bhaney44** [comment]
@iskysun96 `client` is defined in `main.py`:

```
# Client
client = algod.AlgodClient(algod_token, algod_address)
```

**Comment by iskysun96** [comment]
What did you use for algod_token and algod_address? Are you starting up sandbox and connecting to the sandbox node or are you using third party services like purestake of algoexplorer?

**Comment by Bhaney44** [comment]
@iskysun96 The `algo_token` and `algod_address` are defined in the `config.py` file.

`algod_address = "http://localhost:4001"`

I am running a node. I am not completely sure how I defined the `algo_token` variable.

**Comment by iskysun96** [comment]
When you say you are running a node, do you mean you are running sandbox or you built your own node?

Try This. This is for the sandbox node.

`algod_address = "http://localhost:4001"`
`algod_token = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"`
`algod_client = algod.AlgodClient(algod_token, algod_address)`

**Comment by Bhaney44** [comment]
Thanks. I built a node. I am not running in sandbox. Yes - the syntax you are providing is what I am using. Right now I am still handling another [Issue](https://github.com/algorand/py-algorand-sdk/issues/199), which is a requisite for running Layla Coin.

**Comment by ejbaran** [comment]
Sorry for slow reply on this and thanks for pointing this out! Looking into it now. That said, this is an old tutorial that was made with the V1 SDK so I suspect the issues are related to it not being migrated over yet. I'll be migrating it to the V2 SDKs and will update here.

**Comment by Bhaney44** [comment]
Thanks @ejbaran ! You're the best!

**Comment by ejbaran** [comment]
Think I've migrated it all over to v2 (20deb11f9445e3de6d631a04d4bc550ae4b9445d) and updated the [tutorial](https://developer.algorand.org/tutorials/create-dogcoin/ ). I would like to test a little more and review the tutorial more thoroughly but feel free to give it a try and let me know if you're still noticing issues. I ran this with sandbox and py-algorand-sdk 1.5.0. I'll review again tomorrow to make sure.

By the way, there are definitely some style inconsistencies I would like to improve. Happy to take any suggestions or PRs in that regard.

**Comment by ejbaran** [comment]
@miaoye26 as for this error:
`urllib.error.HTTPError: HTTP Error 403: Forbidden`
`algosdk.error.AlgodHTTPError: Missing Authentication Token`

I had a similar issue even after migrating when I used the Purestake API and called the `asset_info()` method on the algod client. May be worth filing an issue there for that. This worked fine with Sandbox.

**Comment by Bhaney44** [comment]
@ejbaran The new code looks great! Thanks again for the update. I am working through the new tutorial now. Specifically, what style inconsistencies would you like to improve? I'm happy to offer suggestions and collaborate on development.

**Comment by Bhaney44** [comment]
Working on figuring out the [REPL](https://en.wikipedia.org/wiki/Read%E2%80%93eval%E2%80%93print_loop). From the tutorial.

_Call this function from the REPL and supply the passphrase of the creator account._
```
from main import create
from config import creator_passphrase
create(creator_passphrase)
```
I tried running this script from `main.py`, `util.py`, `config.py`, a new file called `REPL.py` and from the command line, but have not been successful. I am getting the following error.

```
(AlgoEnv) Brians-MacBook-Pro:create-layla-coin brianhaney$ python3 main.py
b'O\x88\xfd\xf2\xd1\xfe\xee\x96+\xf9\xf0\xb6\xb2\x8d\r\xb5\xced)#\x9bV\xce\xa4\x81\xa6\xb9\xbd\x0e\xf7al'
b'T4j98tH+7pYr+fC2so0Ntc5kKSObVs6kgaa5vQ73YWw='
Traceback (most recent call last):
  File "main.py", line 2, in <module>
    from config import *
  File "/Users/brianhaney/node/algorand-tutorials-python/create-layla-coin/config.py", line 38, in <module>
    from main import create
  File "/Users/brianhaney/node/algorand-tutorials-python/create-layla-coin/main.py", line 7, in <module>
    from util import sign_and_send, balance_formatter
  File "/Users/brianhaney/node/algorand-tutorials-python/create-layla-coin/util.py", line 80, in <module>
    from main import create
ImportError: cannot import name 'create' from 'main' (/Users/brianhaney/node/algorand-tutorials-python/create-layla-coin/main.py) 
```

Still working on this. Any thoughts or suggestions are greatly appreciated!

**Comment by ejbaran** [comment]
@Bhaney44 
Did you mean to run `main.py` or `REPL.py`? And what does the latter file have in it?

The `main.py` wasn't really setup to run. The idea would be to open `python3` and then type the commands line by line. Of course would be nice to just have a script that does all this in one go.

**Comment by Bhaney44** [comment]
I ran both the `main.py` and `REPL.py`. Both files are now yielding the original error. 

`urllib.error.URLError: <urlopen error [Errno 61] Connection refused>`

The code I am stuck on is:

```
from main import create
from config import creator_passphrase
create(creator_passphrase)
```
This code is from the very end of Part III in the [tutorial](https://developer.algorand.org/tutorials/create-dogcoin/). I essentially tried adding the block to the bottom of the `main.py` file. Then, as an alternative, I made the `REPL.py` file with the above code block. The tutorial states "_Call this function from the REPL and supply the passphrase of the creator account._" But, I'm not sure what REPL is referring to, or where to run the script for `create(creator_passphrase)`. 

Thanks again for your help on this @ejbaran - I know you must be super busy and I really appreciate it. I am going to double check to make sure my node is correctly set up and running on the [Testnet](https://testnet.algoexplorer.io/).

**Comment by Bhaney44** [comment]
I opened a pull request to add `run.py` to the tutorial, so we have an executable script. I think the logic is correct. However, on my machine I am still getting an error.

```
(AlgoEnv) Brians-MacBook-Pro:create-layla-coin brianhaney$ python3 run.py
b'O\x88\xfd\xf2\xd1\xfe\xee\x96+\xf9\xf0\xb6\xb2\x8d\r\xb5\xced)#\x9bV\xce\xa4\x81\xa6\xb9\xbd\x0e\xf7al'
b'T4j98tH+7pYr+fC2so0Ntc5kKSObVs6kgaa5vQ73YWw='
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1317, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1016, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 956, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 928, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/socket.py", line 727, in create_connection
    raise err
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run.py", line 17, in <module>
    create(creator_passphrase)
  File "/Users/brianhaney/node/algorand-tutorials-python/create-layla-coin/main.py", line 16, in create
    params = client.suggested_params()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/algosdk/v2client/algod.py", line 278, in suggested_params
    res = self.algod_request("GET", req, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/algosdk/v2client/algod.py", line 72, in algod_request
    resp = urlopen(req)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1345, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1319, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 61] Connection refused>
```

This looks like a Testnet connection issue for my node. I am going to keep working on this and will provide updates as I progress. Thanks again!

**Comment by Bhaney44** [comment]
Good News! My node is running.

```
(base) Brians-MacBook-Pro:~ brianhaney$ source activate algoenv
(algoenv) Brians-MacBook-Pro:~ brianhaney$ export PATH="$HOME/node:$PATH"
(algoenv) Brians-MacBook-Pro:~ brianhaney$ export ALGORAND_DATA="$HOME/node/data"
(algoenv) Brians-MacBook-Pro:~ brianhaney$ goal node start
Algorand node successfully started!
(algoenv) Brians-MacBook-Pro:~ brianhaney$ goal node status
Last committed block: 933025
Time since last block: 0.0s
Sync Time: 0.0s
Last consensus protocol: https://github.com/algorandfoundation/specs/tree/5615adc36bad610c7f165fa2967f4ecfa75125f0
Next consensus protocol: https://github.com/algorandfoundation/specs/tree/5615adc36bad610c7f165fa2967f4ecfa75125f0
Round for next consensus protocol: 933026
Next consensus protocol supported: true
Last Catchpoint:
Genesis ID: testnet-v1.0
Genesis hash: SGO1GKSzyE7IEPItTxCByw9x8FmnrCDexi9/cOUJOiI=
```

The problem is my `Genesis ID` is set to `testnet-v1.0`. I am working on changing it to `testnet-v1.5.0`.

**Comment by ejbaran** [comment]
Catching up here...

Looks like you root caused the issue. Let me know when you've finished updating your TestNet node and how it goes after that!

**Comment by ejbaran** [comment]
Hi @Bhaney44 - just checking in here. I saw on Forums that you tried using algoexplorer API and ran into issues. I haven't used algoexplorer's API, but did you try using [sandbox](https://github.com/algorand/sandbox) yet? That is what I tested with and is pretty straightforward to set up.

**Comment by Bhaney44** [comment]
Hi @ejbaran thanks so much for checking in! 

I posted a [Topic](https://forum.algorand.org/t/url-error-connection-refused/3546) in the Forum for this Issue. I made a small bit of progress, the error I am getting now has changed slightly.

`urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)>`

This is still a URL error and relates to the Network connection. One suggestion was that it may have to do with my local SSL Certificate installations with Python. I installed [Python](https://www.python.org/downloads/) with the standard download. But, I am not sure whether I would need to install the SSL Certificate specifically, or whether there is another way to connect to the Network. 

I just tried running in Sandbox. However, I am getting the same error. I am going to do some digging on SSL Certificates. My initial review suggests there may be a solution out there.

**Comment by Bhaney44** [comment]
We solved it! I launched DogCoin to the [TestNet](https://testnet.algoexplorer.io/tx/WB4DIDBQNVKHX6CQDSAFUVBOXCXWJ5CPTN4GCJJDZLBR2SVQK4QQ).

I needed to update my Python certificates. Running the following from the command line solved the problem.

`open /Applications/Python\ 3.7/Install\ Certificates.command`

Thanks so much for your help @ejbaran !

**Comment by Bhaney44** [comment]
We solved it! I launched DogCoin to the [TestNet](https://testnet.algoexplorer.io/tx/WB4DIDBQNVKHX6CQDSAFUVBOXCXWJ5CPTN4GCJJDZLBR2SVQK4QQ).

I needed to update my Python certificates. Running the following from the command line solved the problem.

`open /Applications/Python\ 3.7/Install\ Certificates.command`

Thanks so much for your help @ejbaran !

**Comment by ejbaran** [comment]
Great news! Happy to help!
